"""added news outlet table

Revision ID: 3ba97a075656
Revises: 990adf1948f0
Create Date: 2024-08-17 22:34:49.416186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba97a075656'
down_revision: Union[str, None] = '990adf1948f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewsOutlets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inUse', sa.Boolean(), nullable=False),
    sa.Column('alwaysJs', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('mainPageCss', sa.String(), nullable=False),
    sa.Column('newsPageCss', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsOutlets')
    # ### end Alembic commands ###
